### ISSUE TITLE
Engine completely crashes when starting on a Vita 6.68

### ISSUE THREAD

**Issue by RibhuNoodleBoodle** [Northfear/gemrb-vita#1]
#### Bug description
The Game crashes on a Vita PCH-2006.

#### Expected behaviour
Well... the game should run and play? 🤷‍♂️ 

#### Unexpected behavior
The game instantly crashes. even with proper configuration:

    VitaCharName = Dude
    VitaPointerSpeed = 10
    
    #####################################################
    #                                                   #
    #  This is the GemRB Configuration file.            #
    #  Here are defined some default parameters for     #
    #  basic configuration and paths definition.        #
    #                                                   #
    #  Parameters are defined as a Name=Value pair      #
    #  The Value can be of three types:                 #
    #      - String                                     #
    #      - Integer                                    #
    #      - Boolean                                    #
    #                                                   #
    #  The String value is represented as follows       #
    #  i.e. H:\GemRB\plugins                            #
    #  Integers are defined as follows                  #
    #  i.e. 12723                                       #
    #  Booleans are represented as 1 or 0 in this file  #
    #                                                   #
    #  Lines starting with # are ignored                #
    #                                                   #
    #####################################################
    
    #####################################################
    #                                                   #
    #  Game Type [String] Use one of the following      #
    #  values:                                          #
    #                                                   #
    #  auto      Attempt to autodetect game type        #
    #                                                   #
    #  bg1       Baldur's Gate                          #
    #  bg2       Baldur's Gate 2 : SoA or ToB           #
    #  how       Icewind Dale : HoW or ToTL             #
    #  (iwd)     Icewind Dale (no How or ToTL installed)#
    #  iwd2      Icewind Dale 2                         #
    #  pst       Planescape Torment                     #
    #                                                   #
    #  demo      Game demo stub                         #
    #  test      Minimal test mode                      #
    #  (More will come)                                 #
    #                                                   #
    #####################################################
    
    GameType=how
    
    #####################################################
    #  Game Name [String] Title for GemRB window, use   #
    #  anything you wish, e.g. Baldur's Gate 3: RotFL   #
    #                                                   #
    #  Defaults to GemRB: <actual game name>            #
    #####################################################
    
    # GameName=Baldur's Gate 2
    
    #####################################################
    #  Encoding [default|polish|czech|german] Language  #
    #  used by game data.                               #
    #####################################################
    
    # Encoding=default
    
    #####################################################
    #  Video Parameters                                 #
    #####################################################
    #NOTE: SCREEN width and height can NOT be ARBITRARY without installing the
    # widescreen mod: http://www.gibberlings3.net/widescreen/
    #Resolutions supported by the original games (gemrb) are:
    # * 640x480 (except in iwd2)
    # * 800x600 (bg2, iwd:how, iwd2)
    # * 1024x768 (bg2, iwd:how, iwd2)
    # * 1280x960 (bg2, iwd:how, iwd2)
    
    #Screen width
    Width=640
    
    #Screen height
    Height=480
    
    #Bits per pixel [Integer:16,32]
    Bpp=32
    
    #Fullscreen [Boolean]
    Fullscreen=1
    
    # Delay before tooltips appear [milliseconds]
    TooltipDelay=500
    
    #####################################################
    #  Audio Parameters                                 #
    #####################################################
    
    # Choices: openal (default), sdlaudio (faster, but limited featureset), none
    AudioDriver = sdlaudio
    
    #####################################################
    #  Case Sensitive Filesystem [Boolean]              #
    #                                                   #
    #  If your installed game files are residing on a   #
    #  case sensitive filesystem (ext2 on Linux) then   #
    #  you need to set this value to 1, it has no       #
    #  effect on Windows                                #
    #####################################################
    
    CaseSensitive=1
    
    #####################################################
    #  GUI Parameters                                   #
    #####################################################
    #                                                   #
    # GemRB may enhance the GUI of the Infinity Engine  #
    # games (so far only in bg2) creating functionally  #
    # new buttons or scrollbars where they weren't      #
    # present in original games. It may improve its     #
    # usability, but is not quite compatible with       #
    # mods changing graphics and alignment in the *.chu #
    # files (e.g. the buttons will appear in old        #
    # coordinates and may stop being clickable).        #
    #####################################################
    
    # Enable all gui enhancements ? [Integer]
    GUIEnhancements = 15
    
    # Enable bigger parties (up to 10) or force smaller ones [Integer]
    # NOTE: You need to choose a big enough resolution, so
    #   there will be enough room for all the party portraits.
    #   THE GAME WILL CRASH OTHERWISE!
    # Requires 10pp mod: https://github.com/lynxlynxlynx/gemrb-mods
    #MaxPartySize = 6
    
    #####################################################
    #  Debug                                            #
    #####################################################
    
    # Do not play intro videos [Boolean], useful for development
    #SkipIntroVideos=1
    
    # Draw Frames per Second info [Boolean]
    DrawFPS=0
    
    # Hide unexplored parts of a map
    #FogOfWar=1
    
    # Enable debug and cheat keystrokes, see docs/en/CheatKeys.txt
    #   full listing
    #EnableCheatKeys=1
    
    #####################################################
    #  Paths                                            #
    #####################################################
    
    #####################################################
    #  Game Paths [String]                              #
    #                                                   #
    #  These are the paths where the Game you want to   #
    #  play is installed.                               #
    #  Enter the full path to the directory.            #
    #                                                   #
    #  Remember, EE versions are not supported!         #
    #####################################################
    
    GamePath=ux0:data/GemRB/iwd
    # only set these if the folders are not in your GamePath
    #CD1=/mnt/windows/Programmi/Black Isle/BGII - SoA/
    #CD2=/mnt/windows/Programmi/Black Isle/BGII - SoA/CD2/
    #CD3=/mnt/windows/Programmi/Black Isle/BGII - SoA/CD3/
    #CD4=/mnt/windows/Programmi/Black Isle/BGII - SoA/CD4/
    #CD5=/mnt/windows/Programmi/Black Isle/BGII - SoA/CD5/
    
    #####################################################
    #  GemRB Cache Path [String]                        #
    #                                                   #
    #  This is the path where GemRB will store the      #
    #  cached files, enter the full path to the GemRB   #
    #  Cache directory.                                 #
    #####################################################
    
    CachePath=ux0:data/GemRB/Cache2/
    
    #####################################################
    #  GemRB Save Path [String]                         #
    #                                                   #
    #  This is the path where GemRB looks for saved     #
    #  games.                                           #
    #  Enter the full path to the directory containing  #
    #  e.g. the 'save' subdirectory.                    #
    #                                                   #
    #  You do not have to specify this if you use save  #
    #  subdir in the GamePath directory.                #
    #####################################################
    
    #SavePath=/mnt/windows/Programmi/Black Isle/BGII - SoA/
    
    ###### HERE BE DRAGONS #############################
    # You shouldn't need to change any paths below this point.
    
    #####################################################
    #  GemRB Path [String]                              #
    #                                                   #
    #  This is the path where GemRB is stored, just     #
    #  enter the full path to the GemRB executable      #
    #####################################################
    
    # preconfigured path
    GemRBPath=ux0:data/GemRB/
    
    # path for official binaries
    GemRBPath=ux0:data/GemRB/
    
    #####################################################
    #  GemRB GUI Scripts Path [String]                  #
    #                                                   #
    #  This is the path where GemRB GUI scripts are     #
    #  stored, usually these are in the GemRB directory #
    #  Enter the full path to the directory containing  #
    #  the 'GUIScript' subdirectory.                    #
    #####################################################
    
    GUIScriptsPath=ux0:data/GemRB/
    
    #####################################################
    #  GemRB Plugins Path [String]                      #
    #                                                   #
    #  This is the path containing GemRB plugins        #
    #  - shared libraries (.so) on Unixes, or           #
    #  DLLs (.dll) on windows.                          #
    #  Enter the full path to the directory.            #
    #                                                   #
    #  You may need to specify this path if running     #
    #  GemRB from source directory on Linux.            #
    #####################################################
    
    PluginsPath=ux0:data/GemRB/plugins/
    
    #####################################################
    #  Custom Font Path [String]                        #
    #                                                   #
    #  This is the path where GemRB looks for non-BAM   #
    #  fonts (ex TTF)                                   #
    #                                                   #
    #####################################################
    
    #CustomFontPath=
    
    #####################################################
    #  Game Data Path [String]                          #
    #                                                   #
    #  This is the subdirectory under GamePath where    #
    #  game data files are stored.                      #
    #                                                   #
    #  You probably do NOT want to specify this!        #
    #####################################################
    
    #GameDataPath=data
    
    #####################################################
    #  Game Data Override Path [String]                 #
    #                                                   #
    #  This is the subdirectory under GamePath where    #
    #  game data override files are stored.             #
    #                                                   #
    #  You probably do NOT want to specify this!        #
    #####################################################
    
    #GameOverridePath=override
    
    #####################################################
    #  GemRB Data Override Path [String]                #
    #                                                   #
    #  This is the path where GemRB looks for the GemRB #
    #  data override directory.                         #
    #                                                   #
    #  You probably do NOT want to specify this!        #
    #####################################################
    
    GemRBOverridePath=ux0:data/GemRB/
    GemRBUnhardcodedPath=ux0:data/GemRB/
    
    #####################################################
    #  Input Parameters                                 #
    #####################################################
    
    #whether or not to use software keyboard on devices that support one
    #UseSoftKeyboard=1
    
    #Adds a gutter around the screen for scrolling
    #TouchScrollAreas=1
    
    #####################################################
    #  MouseFeedback                                    #
    #  Bitfield with reserved bits for disabling        #
    #  the mouse. Those bits cannot be set via config   #
    #                                                   #
    #  Show mouse+tooltips = 0                          #
    #  Hide mouse          = 1                          #
    #  Hide tooltips       = 2                          #
    #  Hide mouse+tooltips = 3                          #
    #####################################################
    
    # For a strictly touchscreen device we recommend
    # Changing this to 3.
    
    # default is 0
    #MouseFeedback=0
    
    #####################################################
    #  Touch Gesture Input Parameters                   #
    #  Requires SDL 1.3 or later                        #
    #  All "NumFing" settings must be > 1 and < 5       #
    #  NumFingScroll and NumFingKboard cannot be equal  #
    #####################################################
    
    #NumFingScroll=2
    
    #NumFingKboard=3
    
    #NumFingInfo=2
    
    #####################################################
    #  END                                              #
    #####################################################

#### Screenshots

![2020-09-16-164051](https://user-images.githubusercontent.com/63103811/93329977-abf5e800-f83b-11ea-93ee-a6370ebe509c.jpg)

**Comment by Northfear** [comment]
@ribhutheincompetent Hey! Can you upload psp2dmp file somewhere?
I suspect that this is some 3.68 compatibility thing (not sure if anything can be done about it, but I'll look into it)

**Comment by RibhuNoodleBoodle** [comment]
> @ribhutheincompetent Hey! Can you upload psp2dmp file anywhere?
> I suspect that this is some 3.68 compatibility thing (not sure if anything can be done about it, but I'll look into it)

Yeah, sure why not

[psp2core-1600288805-0x0004d02b6d-eboot.bin.psp2dmp.gz](https://github.com/Northfear/gemrb-vita/files/5246990/psp2core-1600288805-0x0004d02b6d-eboot.bin.psp2dmp.gz)

I've temp added a .gz suffix, pretty sure removing it through renaming would suffice, no?

**Comment by Northfear** [comment]
Lets try this build first. I've switched SDKs since last release and this change alone fixed some weird bugs.
[gemrb_build.zip](https://github.com/Northfear/gemrb-vita/files/5249741/gemrb_build.zip)
If it still fails, could you please send me gemrb.log (it's inside game folder).
And does it works with other games BTW?

**Comment by RibhuNoodleBoodle** [comment]
Hey, 

I'm currently busy with folks so I'll test and ping you a little bit later. As for games: I'm currently trying both Icewind Dale Complete and an the non-EE Planescape Torment.

**Comment by RibhuNoodleBoodle** [comment]
I've only tested PST so far and holy mongolia, it runs really well. Granted I disabled the sound driver this time since I wanted to so some backbench gaming in the class (lol) but the game itself runs very well!

![2020-09-19-174436](https://user-images.githubusercontent.com/63103811/93667657-44db6c00-faa5-11ea-9607-4bb1a138707f.jpg)

There are some issues however like if I suspend and resume the system it the script basically breaks:

![2020-09-19-175004](https://user-images.githubusercontent.com/63103811/93667702-8835da80-faa5-11ea-9ab2-ff5898114230.jpg)

![2020-09-19-1740581](https://user-images.githubusercontent.com/63103811/93667708-8ff57f00-faa5-11ea-9b12-992c14fbfc11.jpg)

Also, It seems it can't playback any video cutscenes (which I think is a major bug)

and I also can't see number on the dialogue but since I'm not using a keyboard it hardly matters to me 
🤷 (and this is an arbitrary nitpick so you can ignore it lol)

And as you wanted:

[GemRB.log](https://github.com/Northfear/gemrb-vita/files/5249874/GemRB.log)

Hope this helps!

**Comment by Northfear** [comment]
For suspend/resume support install this plugin
https://github.com/dots-tb/rePatch-reDux0
As for the videos I'll try checking it later, since I haven't tested PST on Vita before

**Comment by Northfear** [comment]
Videos are working fine for me. Make sure that they're present, because there's some error while opening them
`[Unknown]: Cannot open archive ux0:data/GemRB/pst/data/genmovB.bif`
"number on the dialogue" could be upstream thing, so we may have to wait for the fix.
I'm sorry that I can't help you any further with the videos. I only have 3.60 Vita and since it's the only "officially" supported one, compatibility with newer firmware versions may vary.
I'm closing this for now, since it's at least launching now.
