### ISSUE TITLE
TTF Support 

### ISSUE THREAD

**Issue by einmueller** [Northfear/gemrb-vita#3]
#### Description
The Text is nearly unreadable for my old eyes

#### Additional context
The Text is very small on vita, so very hard to read. I known, it is a fixed font by default, but I read, the gemrb supports TrueType-Fonts also and could use bigger fonts that way. In your instructions, you use "-DUSE_FREETYPE=false", so I guess, not Chance of using TTF at the moment. But is there perhaps a little Chance to activate TTF in the build and to use some bigger fonts?

Greetings and happy hacking,

SirTobi

**Comment by Northfear** [comment]
Honestly I can't even remember why it's `-DUSE_FREETYPE=false` at this point, but I'll try to look into it

**Comment by Northfear** [comment]
@einmueller TTF support was added in latest release
https://github.com/Northfear/gemrb-vita/releases/tag/v0.8.7-vita.5
No idea how functional it is (GemRB demo worked well. Haven't tested beyond that)

**Comment by dagdha2002** [comment]
Sorry, I know that this issue is closed, but I´m trying to contact with einmueller for something related with his Exult Vita port and I´m out of ideas of how contact with him. Sorry Northfear for bothering here...
