### ISSUE TITLE
Refuses to run Planescape Torment. 

### ISSUE THREAD

**Issue by aknight2015** [Northfear/gemrb-vita#4]
I copied the entire directory of Planscape Torment (enhanced edition 3.0.3.0 (11051)) into the ux0:data/GemRB/PST/ folder. I run GemRB, tap Planescape Torment, it just goes back to the launcher.

**Comment by Northfear** [comment]
Only original games are supported by GemRB right now
https://gemrb.org/Features.html#status
So enhanced editions won't work unfortunately
