### ISSUE TITLE
tts plugin support for using other language data files? 

### ISSUE THREAD

**Issue by kane159** [Northfear/gemrb-vita#5]
#### Description
Add a clear and concise description of what the missing feature is. Eg. the
original supported NPC bumping when pathfinding, but GemRB doesn't.
for now i am trying to play pst by using my good old 4 cd Taiwan release
and it runs pretty well but no text can be shown

**Comment by Northfear** [comment]
TTF is supported in the last few Vita releases. I guess this article is probably relevant:
https://gemrb.org/Text-encodings.html
Try following it and maybe using custom fonts if nothing works.
Is it reproducible with PC version of GemRB too? Or is it Vita only issue?

PS. Even with working fonts PST support is still pretty limited in GemRB (especially in 0.8.8 version)
